security.jwt.token.secret-key: my-secret-key
spring:
    application:
        name: myMaster
    datasource:
      url: jdbc:mysql://localhost:3306/mymaster
      username: root
      password: root
    flyway:
      enabled: true
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
server:
  tomcat:
    max-swallow-size: 100MB