security.jwt.token.secret-key: my-secret-key
spring:
    application:
        name: myMaster
    datasource:
      url: jdbc:mysql://localhost:3306/mymaster
      username: root
      password: root
    flyway:
      enabled: true
